#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-mongo
Version  : 2.0.6
Release  : 6
URL      : https://rubygems.org/downloads/mongo-2.0.6.gem
Source0  : https://rubygems.org/downloads/mongo-2.0.6.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
BuildRequires : ruby
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-bson
BuildRequires : rubygem-coveralls
BuildRequires : rubygem-docile
BuildRequires : rubygem-domain_name
BuildRequires : rubygem-http-cookie
BuildRequires : rubygem-i18n
BuildRequires : rubygem-metaclass
BuildRequires : rubygem-mime-types
BuildRequires : rubygem-minitest
BuildRequires : rubygem-mocha
BuildRequires : rubygem-netrc
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rest-client
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-shoulda
BuildRequires : rubygem-shoulda-context
BuildRequires : rubygem-shoulda-matchers
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-simplecov-html
BuildRequires : rubygem-term-ansicolor
BuildRequires : rubygem-test-unit
BuildRequires : rubygem-thor
BuildRequires : rubygem-thread_safe
BuildRequires : rubygem-tins
BuildRequires : rubygem-tzinfo
BuildRequires : rubygem-unf
BuildRequires : rubygem-unf_ext

%description
MongoDB Ruby Driver [![Build Status][travis-img]][travis-url] [![Code Climate][codeclimate-img]][codeclimate-url] [![Coverage Status][coveralls-img]][coveralls-url] [![Gem Version][rubygems-img]][rubygems-url]
-----
The officially supported Ruby driver for [MongoDB](http://www.mongodb.org).

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n mongo-2.0.6
gem spec %{SOURCE0} -l --ruby > rubygem-mongo.gemspec

%build
gem build rubygem-mongo.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
mongo-2.0.6.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/mongo-2.0.6.gem
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/README.md
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/bin/mongo_console
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/address.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/address/ipv4.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/address/ipv6.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/address/unix.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/auth.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/auth/cr.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/auth/cr/conversation.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/auth/ldap.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/auth/ldap/conversation.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/auth/roles.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/auth/scram.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/auth/scram/conversation.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/auth/user.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/auth/user/view.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/auth/x509.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/auth/x509/conversation.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/bulk_write.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/bulk_write/bulk_writable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/bulk_write/deletable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/bulk_write/insertable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/bulk_write/ordered_bulk_write.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/bulk_write/replacable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/bulk_write/unordered_bulk_write.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/bulk_write/updatable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/client.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/cluster.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/cluster/topology.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/cluster/topology/replica_set.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/cluster/topology/sharded.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/cluster/topology/single.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/cluster/topology/unknown.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/collection/view.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/collection/view/aggregation.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/collection/view/explainable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/collection/view/immutable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/collection/view/iterable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/collection/view/map_reduce.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/collection/view/readable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/collection/view/writable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/cursor.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/database.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/database/view.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/bulk_write_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/invalid_bulk_operation.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/invalid_bulk_operation_type.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/invalid_collection_name.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/invalid_database_name.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/invalid_document.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/invalid_file.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/invalid_nonce.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/invalid_replacement_document.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/invalid_server_preference.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/invalid_signature.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/invalid_update_document.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/invalid_uri.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/invalid_uri_option.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/max_bson_size.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/max_message_size.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/multi_index_drop.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/need_primary_server.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/no_server_available.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/operation_failure.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/socket_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/socket_timeout_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/error/unsupported_features.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/event.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/event/description_changed.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/event/listeners.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/event/primary_elected.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/event/publisher.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/event/standalone_discovered.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/event/subscriber.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/grid.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/grid/file.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/grid/file/chunk.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/grid/file/metadata.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/grid/fs.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/index.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/index/view.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/loggable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/logger.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/aggregate.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/aggregate/result.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/command.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/executable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/kill_cursors.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/limited.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/list_collections/result.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/list_indexes/result.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/map_reduce.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/map_reduce/result.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/read.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/read/collections_info.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/read/get_more.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/read/indexes.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/read/list_collections.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/read/list_indexes.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/read/query.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/read_preferrable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/result.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/specifiable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/bulk.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/bulk/bulk_delete.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/bulk/bulk_delete/result.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/bulk/bulk_insert.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/bulk/bulk_insert/result.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/bulk/bulk_mergable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/bulk/bulk_update.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/bulk/bulk_update/result.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/bulk/legacy_bulk_mergable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/command.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/command/create_index.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/command/create_user.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/command/delete.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/command/drop_index.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/command/insert.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/command/remove_user.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/command/update.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/command/update_user.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/command/writable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/create_index.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/create_user.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/delete.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/delete/result.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/drop_index.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/idable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/insert.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/insert/result.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/remove_user.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/update.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/update/result.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/operation/write/update_user.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/options/mapper.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/protocol.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/protocol/bit_vector.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/protocol/delete.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/protocol/get_more.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/protocol/insert.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/protocol/kill_cursors.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/protocol/message.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/protocol/query.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/protocol/reply.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/protocol/serializers.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/protocol/update.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server/connectable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server/connection.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server/connection_pool.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server/connection_pool/queue.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server/context.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server/description.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server/description/features.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server/description/inspector.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server/description/inspector/description_changed.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server/description/inspector/primary_elected.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server/description/inspector/standalone_discovered.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server/monitor.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server/monitor/connection.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server_selector.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server_selector/nearest.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server_selector/primary.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server_selector/primary_preferred.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server_selector/secondary.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server_selector/secondary_preferred.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/server_selector/selectable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/socket.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/socket/ssl.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/socket/tcp.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/socket/unix.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/uri.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/write_concern.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/write_concern/acknowledged.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/write_concern/normalizable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/lib/mongo/write_concern/unacknowledged.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/mongo.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/address/ipv4_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/address/ipv6_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/address/unix_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/address_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/auth/cr_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/auth/ldap_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/auth/scram/conversation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/auth/scram_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/auth/user/view_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/auth/user_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/auth/x509_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/auth_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/bulk/bulk_write_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/client_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/cluster/topology/replica_set_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/cluster/topology/sharded_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/cluster/topology/single_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/cluster/topology/unknown_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/cluster/topology_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/cluster_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/collection/view/aggregation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/collection/view/explainable_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/collection/view/map_reduce_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/collection/view/readable_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/collection/view/writable_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/collection/view_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/collection_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/crud_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/cursor_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/database_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/error/parser_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/event/publisher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/event/subscriber_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/grid/file/chunk_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/grid/file/metadata_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/grid/file_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/grid/fs_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/index/view_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/loggable_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/logger_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/aggregate/result_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/aggregate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/command_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/kill_cursors_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/limited_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/map_reduce_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/read/collections_info_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/read/get_more_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/read/indexes_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/read/query_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/read_preferrable_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/result_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/specifiable_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/write/bulk/bulk_delete_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/write/bulk/bulk_insert_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/write/bulk/bulk_update_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/write/command/delete_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/write/command/insert_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/write/command/update_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/write/create_index_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/write/create_user_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/write/delete_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/write/drop_index_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/write/insert_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/write/remove_user_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/write/response_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/write/update_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/operation/write/update_user_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/protocol/delete_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/protocol/get_more_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/protocol/insert_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/protocol/kill_cursors_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/protocol/query_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/protocol/reply_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/protocol/update_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server/connection_pool/queue_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server/connection_pool_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server/connection_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server/description/features_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server/description/inspector/description_changed_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server/description/inspector/primary_elected_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server/description_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server/monitor_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server_discovery_and_monitoring_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server_selection_rtt_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server_selection_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server_selector/nearest_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server_selector/primary_preferred_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server_selector/primary_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server_selector/secondary_preferred_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server_selector/secondary_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server_selector_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/server_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/socket/ssl_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/uri_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/write_concern/acknowledged_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/mongo/write_concern/unacknowledged_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/authorization.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/certificates/ca.pem
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/certificates/client.pem
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/certificates/crl.pem
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/certificates/crl_client_revoked.pem
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/certificates/password_protected.pem
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/certificates/server.pem
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud/read.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud/write.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud_tests/read/aggregate.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud_tests/read/count.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud_tests/read/distinct.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud_tests/read/find.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud_tests/write/deleteMany.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud_tests/write/deleteOne.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud_tests/write/findOneAndDelete.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud_tests/write/findOneAndReplace.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud_tests/write/findOneAndUpdate.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud_tests/write/insertMany.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud_tests/write/insertOne.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud_tests/write/replaceOne.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud_tests/write/updateMany.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/crud_tests/write/updateOne.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/discover_arbiters.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/discover_passives.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/discover_primary.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/discover_secondary.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/discovery.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/ghost_discovered.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/hosts_differ_from_seeds.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/member_reconfig.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/member_standalone.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/new_primary.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/new_primary_wrong_set_name.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/non_rs_member.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/normalize_case.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/primary_becomes_standalone.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/primary_changes_set_name.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/primary_disconnect.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/primary_wrong_set_name.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/response_from_removed.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/rsother_discovered.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/sec_not_auth.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/secondary_wrong_set_name.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/secondary_wrong_set_name_with_primary.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/unexpected_mongos.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/rs/wrong_set_name.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/sharded/multiple_mongoses.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/sharded/non_mongos_removed.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/sharded/normalize_uri_case.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/sharded/single_mongos.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/single/direct_connection_external_ip.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/single/direct_connection_mongos.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/single/direct_connection_rsarbiter.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/single/direct_connection_rsprimary.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/single/direct_connection_rssecondary.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/single/direct_connection_slave.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/single/direct_connection_standalone.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/single/not_ok_response.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/single/standalone_removed.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/sdam/single/unavailable_seed.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_discovery_and_monitoring.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/rtt/first_value.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/rtt/first_value_zero.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/rtt/value_test_1.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/rtt/value_test_2.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/rtt/value_test_3.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/rtt/value_test_4.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/rtt/value_test_5.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetNoPrimary/read/Nearest.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetNoPrimary/read/Nearest_non_matching.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetNoPrimary/read/Primary.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetNoPrimary/read/PrimaryPreferred.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetNoPrimary/read/PrimaryPreferred_non_matching.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetNoPrimary/read/Secondary.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetNoPrimary/read/SecondaryPreferred.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetNoPrimary/read/SecondaryPreferred_non_matching.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetNoPrimary/read/Secondary_non_matching.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetWithPrimary/read/Nearest.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetWithPrimary/read/Nearest_non_matching.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetWithPrimary/read/Primary.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetWithPrimary/read/PrimaryPreferred.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetWithPrimary/read/PrimaryPreferred_non_matching.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetWithPrimary/read/Secondary.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetWithPrimary/read/SecondaryPreferred.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetWithPrimary/read/SecondaryPreferred_non_matching.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/ReplicaSetWithPrimary/read/Secondary_non_matching.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/Sharded/read/SecondaryPreferred.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/Single/read/SecondaryPreferred.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection/selection/Unknown/read/SecondaryPreferred.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/server_selection_rtt.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/shared/bulk_write.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/shared/cursor.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/shared/operation.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/shared/protocol.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/shared/server_selector.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/shared/socket.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo-2.0.6/spec/support/travis.rb
/usr/lib64/ruby/gems/2.3.0/specifications/mongo-2.0.6.gemspec
